name: Freie check
on:
  schedule:
  - cron:  '* 1 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest version
        run: |
          curl http://www.freie-schule-schoeneberg.de/anmeldung.html > schools/freie.html
      - name: Push Changes
        run: |
          git config user.name "freie_bot"
          git config user.email "freie_bot@users.noreply.github.com"
          git add .
          git commit -m "Freie: add a new version" || echo "No changes to commit"
          git push
