name: HVOB check
on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get latest version
        run: |
          curl -s https://www.hvob-music.com/dates.js | sed 's/<br>/\n/g' | head | grep -v span > files/hvob.html
      - name: Push Changes
        run: |
          git config user.name "hvob_bot"
          git config user.email "HVOB_bot@users.noreply.github.com"
          git add .
          git commit -m "HVOB: add a new version" || echo "No changes to commit"
          git push || echo "No changes to push"
