on:
  schedule:
    - cron:  '* 12 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check new version
        run: |
          curl -s https://www.bdk-schoeneberg.de/bewerbungkleingaerten > page.html
          git add .
          git commit -m "Add a new version"
      - name: Push Changes
        if: ${{ success() }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git push