name: Check Offers
on:
  schedule:
  - cron:  '*/20 * 7-20 * 1-5'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      URL: https://inberlinwohnen.de/wp-content/themes/ibw/skript/wohnungsfinder.php
      QUERY: q=wf-save-srch&qm_min=100
      delimiter: ",["
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get latest version
        run: |
          git config user.name "offer_bot"
          git config user.email "offer_bot@users.noreply.github.com"
          result=$(curl -s $URL  -c /dev/null --data-raw $QUERY | jq -r '.addmarkers')

          s=$result$delimiter
          offers=();
          while [[ $s ]]; do
              offers+=( "${s%%"$delimiter"*}" );
              s=${s#*"$delimiter"};
          done;

          for offer in "${offers[@]}"; do
            offer=`echo $offer | sed 's/\[//g' | sed 's/]//g'`
            filename=`echo $offer | md5sum | cut -f1 -d" "`
            text=`echo $offer | cut -f6 -d"'" | cut -f1 -d"&" | sed -e 's/<[^>]*>//g'`
            echo $offer > offers/$filename
            git add offers/$filename
            git commit -m "$text"
            git push
          done
