name: Get latest version and commit changes
on:
  schedule:
  - cron:  '* 1 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest version
        run: |
          curl https://www.freudbergschule.de/infoabend/ | awk -v RS="" '{split($0,a,"</html>"); print a[1]}' > schools/freudberg.html
      - name: Push Changes
        run: |
          git config user.name "freudberg_bot"
          git config user.email "freudberg_bot@users.noreply.github.com"
          git add .
          git commit -m "Freudberg: add a new version" || echo "No changes to commit"
          git push
