name: Get latest version and commit changes
on:
  schedule:
  - cron:  '0 18 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest version
        run: |
          curl https://www.bdk-schoeneberg.de/bewerbungkleingaerten/ > page.html
          OUT=`cat page.html| sed -n 's/<a href="/\n/gp' | sed -n 's/">/\n/gp' | grep Freie_Kleingaerten`
          curl -sO https://www.bdk-schoeneberg.de$OUT
          mv *.pdf files/
      - name: Push Changes
        run: |
          git config user.name "kleingarten_bot"
          git config user.email "kleingarten_bot@users.noreply.github.com"
          git add .
          git commit -m "Add a new version" || echo "No changes to commit"
          git push
